---
sidebar: sidebar 
permalink: scpivs44_rest_apis__download_jobs_and_generate_reports.html 
keywords:  
summary: Zum Generieren von Berichten und Herunterladen von Protokollen für VMware vSphere Client-Jobs mithilfe des SnapCenter Plug-ins für VMware vSphere REST-APIs müssen SIE DIE REST-API-Aufrufe für VMware vSphere verwenden. 
---
= REST-APIs zum Herunterladen von Jobs und zum Generieren von Berichten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Zum Generieren von Berichten und Herunterladen von Protokollen für VMware vSphere Client-Jobs mithilfe des SnapCenter Plug-ins für VMware vSphere REST-APIs müssen SIE DIE REST-API-Aufrufe für VMware vSphere verwenden.

Fügen Sie für jede REST-API an der Vorderseite der REST-API hinzu `\https://<server>:<port>` , um einen vollständigen Endpunkt zu bilden.



== Verwenden Sie die folgenden REST-APIs im Abschnitt Jobs, um detaillierte Informationen über Jobs zu erhalten:

|===
| REST API | Kommentare 


| `/4.1/jobs` | `Get all jobs` Ruft die Jobdetails für mehrere Jobs ab. Sie können den Umfang der Anforderung einschränken, indem Sie einen Jobtyp angeben, z. B. `backup`, `mountBackup`oder `restore`. 


| `/4.1/jobs/{id}` | `Get job details` Ruft detaillierte Informationen für den angegebenen Job ab. 
|===


== Verwenden Sie die folgende REST-API im Abschnitt Jobs zum Herunterladen von Jobprotokollen:

|===
| REST API | Kommentare 


| `/4.1/jobs/{id}/logs` | `getJobLogsById` lädt die Protokolle für den angegebenen Job herunter. 
|===


== Verwenden Sie die folgenden REST-APIs im Abschnitt Berichte zum Generieren von Berichten:

|===
| REST API | Kommentare 


| `4.1/reports/protectedVM` | `Get Protected VM List` Ruft eine Liste der geschützten VMs der letzten sieben Tage ab. 


| `/4.1/reports/
unProtectedVM` | `Get Unprotected VM List` Ruft eine Liste der ungeschützten VMs der letzten sieben Tage ab. 
|===