---
sidebar: sidebar 
permalink: scpivs44_properties_you_can_override.html 
keywords:  
summary: 'Sie können die in der Konfigurationsdatei aufgeführten Eigenschaften verwenden `scbr.override` , um die Standardwerte zu ändern.' 
---
= Eigenschaften, die Sie überschreiben können
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die in der Konfigurationsdatei aufgeführten Eigenschaften verwenden `scbr.override` , um die Standardwerte zu ändern.

* Standardmäßig verwendet die Vorlage Hash-Symbol, um die Konfigurationseigenschaften zu kommentieren. Um einen Konfigurationswert mit einer Eigenschaft zu ändern, müssen Sie die Zeichen entfernen `#` .
* Sie müssen den Service auf dem SnapCenter Plug-in für VMware vSphere Host neu starten, damit die Änderungen wirksam werden.


Sie können die folgenden Eigenschaften verwenden, die in der Konfigurationsdatei aufgeführt sind `scbr.override` , um die Standardwerte zu ändern.

* *dashboard.protected.vm.count.interval=7*
+
Gibt die Anzahl der Tage an, für die das Dashboard den VM-Schutzstatus anzeigt.

+
Der Standardwert ist „7“.

* *Deaktivier.schwächCiphers=true*
+
Deaktiviert die folgenden Schwächungskipher für den Kommunikationskanal zwischen SnapCenter Plug-in für VMware vSphere und SnapCenter sowie alle zusätzlichen Schwächungskipher, die in aufgeführt sind `include.weakCiphers`: TLS_128 RSA_WITH_128 AES_256 128 128_CBC_SHA256_SHA256_TLS_DHE_RSA_256 256_SHA256_SHA256_SHA256_AES_SHA256_SHA256_SHA256_SHA256_SHA256_TLS_SHA256_SHA256_SHA24_SHA24_SHA24_SHA24_SHA24_SHAEB6_SHA24_SHA24_SHAEB6_SHA24_SHA24_SHA24_SHA24_SHAEBS256

* *Global.ds.exclusion.pattern*
+
Gibt einen oder mehrere herkömmliche oder vVol Datastores an, die von Backup-Vorgängen ausgeschlossen werden sollen. Sie können die Datenspeicher mit jedem gültigen Java-regulären Ausdruck angeben.

+
Beispiel 1: Der Ausdruck `global.ds.exclusion.pattern=.*21` schließt Datastores aus, die ein allgemeines Muster haben, z. B. `datastore21` und `dstest21` würden ausgeschlossen werden.

+
Beispiel 2: Der Ausdruck `global.ds.exclusion.pattern=ds-.*|^vol123` schließt alle Datastores aus, die (zum Beispiel) enthalten `ds-` `scvds-test`oder mit beginnen `vol123`.

* *guestFileRestore.guest.operation.interval=5*
+
Gibt das Zeitintervall in Sekunden an, das SnapCenter Plug-in für VMware vSphere zum Abschluss von Gastoperationen auf dem Gastsystem überwacht (Online-Festplatte und Restore-Dateien). Die gesamte Wartezeit wird von und festgelegt `guestFileRestore.online.disk.timeout` `guestFileRestore.restore.files.timeout`.

+
Der Standardwert ist „5“.

* *GuestFileRestore.MonitorIntervall=30*
+
Gibt das Zeitintervall in Minuten an, das das SnapCenter Plug-in für VMware vSphere für die Wiederherstellung abgelaufener Gastdateien überwacht. Jede Sitzung, die über die konfigurierte Sitzungszeit hinaus ausgeführt wird, wird getrennt.

+
Der Standardwert ist „30“.

* *GuestFileRestore.online.Disk.Timeout=100*
+
Gibt die Zeit in Sekunden an, die das SnapCenter-Plug-in für VMware vSphere auf den Abschluss eines Online-Festplattenvorgangs auf einer Gast-VM wartet. Beachten Sie, dass es eine weitere 30-Sekunden-Wartezeit gibt, bevor das Plug-in abfragt, um den Online-Festplattenvorgang abgeschlossen zu haben.

+
Der Standardwert ist „100“.

* *GuestFileRestore.restore.files.Timeout=3600*
+
Gibt die Zeit in Sekunden an, die das SnapCenter-Plug-in für VMware vSphere auf den Abschluss eines Wiederherstellungsvorgangs auf einer Gast-VM wartet. Wenn die Zeit überschritten wird, wird der Prozess beendet und der Job als fehlgeschlagen markiert.

+
Der Standardwert ist "3600" (1 Stunde).

* *GuestFileRestore.robotcopy.Directory.Flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP*
+
Gibt die zusätzlichen robocopy-Flags an, die beim Kopieren von Verzeichnissen während der Wiederherstellung von Gastdateien verwendet werden sollen.

+
Entfernen oder hinzufügen Sie nicht `/NJH` `/NJS` , da dadurch die Analyse der Wiederherstellungsausgabe unterbrochen wird.

+
Erlauben Sie keine unbegrenzten Wiederholungen (durch Entfernen des `/R` Flags), da dies zu endlosen Wiederholungen für fehlgeschlagene Kopien führen kann.

+
Die Standardwerte sind `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP"` .

* *GuestFileRestore.robotcopy.file.Flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP*
+
Gibt die zusätzlichen robocopy-Flags an, die beim Kopieren einzelner Dateien während der Wiederherstellung von Gastdateien verwendet werden sollen.

+
Entfernen oder hinzufügen Sie nicht `/NJH` `/NJS` , da dadurch die Analyse der Wiederherstellungsausgabe unterbrochen wird.

+
Erlauben Sie keine unbegrenzten Wiederholungen (durch Entfernen des `/R` Flags), da dies zu endlosen Wiederholungen für fehlgeschlagene Kopien führen kann.

+
Die Standardwerte sind `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP"`.

* *guestFileRestore.sessionTime=1440*
+
Gibt die Zeit in Minuten an, zu der das SnapCenter Plug-in für VMware vSphere eine Wiederherstellungssitzung für Gastdateien aktiv hält.

+
Der Standardwert ist "1440" (24 Stunden).

* *guestFileRestore.use.custom.online.disk.script=true*
+
Gibt an, ob beim Erstellen von Sitzungen zur Wiederherstellung von Gastdateien ein benutzerdefiniertes Skript zum Einlegen von Datenträgern und Abrufen von Laufwerksbuchstaben verwendet werden soll. Das Skript muss sich unter befinden `[Install Path]  \etc\guestFileRestore_onlineDisk.ps1`. Bei der Installation wird ein Standardskript bereitgestellt. Die Werte `[Disk_Serial_Number]`, `[Online_Disk_Output]`und `[Drive_Output]` werden während des Anhängevorgangs im Skript ersetzt.

+
Der Standardwert ist „false“.

* *include.esx.initiator.id.from.cluster=true*
+
Gibt an, dass das SnapCenter-Plug-in für VMware vSphere iSCSI- und FCP-Initiator-IDs von allen ESXi-Hosts im Cluster in der Anwendung über VMDK-Workflows enthalten sollte.

+
Der Standardwert ist „false“.

* *Include.schwächCiphers*
+
Wenn `disable.weakCiphers` auf , festgelegt ist `true`, gibt die schwachen Chiffren an, die deaktiviert werden sollen, zusätzlich zu den schwachen Chiffren, die standardmäßig deaktiviert werden `disable.weakCiphers` .

* *Max.Concurrent.ds.Storage.query.count=15*
+
Gibt die maximale Anzahl gleichzeitiger Anrufe an, die das SnapCenter-Plug-in für VMware vSphere am SnapCenter-Server durchführen kann, um den Speicherplatzbedarf für die Datastores zu ermitteln. Das Plug-in führt diese Aufrufe aus, wenn Sie den Linux-Dienst auf dem SnapCenter-Plug-in für VMware vSphere VM-Host neu starten.

* *nfs.Datastore.Mount.retry.count=3*
+
Gibt die maximale Anzahl der Versuche an, die das SnapCenter-Plug-in für VMware vSphere versucht, ein Volume als NFS-Datastore in vCenter zu mounten.

+
Der Standardwert ist „3“.

* *nfs.datastore.mount.retry.delay=60000*
+
Gibt die Zeit in Millisekunden an, die das SnapCenter-Plug-in für VMware vSphere zwischen den Versuchen wartet, ein Volume als NFS-Datastore in vCenter zu mounten.

+
Der Standardwert ist „60000“ (60 Sekunden).

* *script.virtual.machine.count.variable.name= VIRTUELLE_MASCHINEN*
+
Gibt den Namen der Umgebungsvariable an, der die Anzahl der virtuellen Maschinen enthält. Sie müssen die Variable definieren, bevor Sie während eines Backup-Jobs benutzerdefinierte Skripte ausführen.

+
BEISPIELSWEISE bedeutet VIRTUAL_MACHINES=2, dass zwei virtuelle Maschinen gesichert werden.

* *script.virtual.machine.info.variable.name=VIRTUAL_MACHINE.%s*
+
Gibt den Namen der Umgebungsvariable an, die Informationen über die n. Virtuelle Maschine im Backup enthält. Sie müssen diese Variable festlegen, bevor Sie während einer Sicherung benutzerdefinierte Skripts ausführen.

+
Beispielsweise liefert die Umgebungsvariable VIRTUAL_MACHINE.2 Informationen über die zweite virtuelle Maschine im Backup.

* * script.virtual.machine.info.format= %s *
+
Stellt Informationen zur virtuellen Maschine bereit. Das Format für diese Informationen, das in der Umgebungsvariable festgelegt wird, ist das folgende: `VM name|VM UUID| VM power state (on|off)|VM snapshot taken (true|false)|IP address(es)`

+
Im Folgenden finden Sie ein Beispiel für die Informationen, die Sie bereitstellen können:

+
`VIRTUAL_MACHINE.2=VM 1|564d6769-f07d-6e3b-68b1f3c29ba03a9a|POWERED_ON||true|10.0.4.2`

* *Storage.connection.Timeout=600000*
+
Gibt den Zeitraum in Millisekunden an, den der SnapCenter-Server auf eine Antwort des Storage-Systems wartet.

+
Der Standardwert ist "600000" (10 Minuten).

* *vmware.esx.ip.kernel.ip.map*
+
Es gibt keinen Standardwert. Sie verwenden diesen Wert, um die ESXi-Host-IP-Adresse der VMkernel-IP-Adresse zuzuordnen. Standardmäßig verwendet das SnapCenter-Plug-in für VMware vSphere die Management-VMkernel-Adapter-IP-Adresse des ESXi-Hosts. Wenn das SnapCenter-Plug-in für VMware vSphere eine andere VMkernel-Adapter-IP-Adresse verwenden soll, müssen Sie einen Überschreibungswert angeben.

+
Im folgenden Beispiel ist die IP-Adresse des Management-VMkernel-Adapters 10.225.10.56. Das SnapCenter-Plug-in für VMware vSphere verwendet jedoch die angegebene Adresse 10.225.11.57 und 10.225.11.58. Und wenn die Management-VMkernel-Adapter-IP-Adresse 10.225.10.60 ist, verwendet das Plug-in die Adresse 10.225.11.61.

+
`vmware.esx.ip.kernel.ip.map=10.225.10.56:10.225.11.57,10.225.11.58; 10.225.10.60:10.225.11.61`

* *vmware.max.Concurrent.Snapshots=30*
+
Gibt die maximale Anzahl gleichzeitiger VMware-Snapshots an, die das SnapCenter-Plug-in für VMware vSphere auf dem Server durchführt.

+
Diese Zahl wird pro Datenspeicher geprüft und nur dann aktiviert, wenn für die Richtlinie „VM-konsistent“ ausgewählt ist. Wenn Sie absturzkonsistente Backups durchführen, gilt diese Einstellung nicht.

+
Der Standardwert ist „30“.

* *vmware.max.concurrent.snapshots.delete=30*
+
Gibt die maximale Anzahl gleichzeitiger VMware-Snapshot-Löschvorgänge pro Datastore an, die das SnapCenter-Plug-in für VMware vSphere auf dem Server ausführt.

+
Diese Nummer wird pro Datenspeicher geprüft.

+
Der Standardwert ist „30“.

* *vmware.query.unresolved.retry.count=10*
+
Gibt die maximale Anzahl von Versuchen an, die das SnapCenter-Plug-in für VMware vSphere wiederholt versucht, eine Abfrage über nicht aufgelöste Volumes zu senden, weil „...Zeitlimit für das Abhalten von I/O...“ Fehler.

+
Der Standardwert ist „10“.

* *vmware.quiesce.retry.count=0*
+
Gibt die maximale Anzahl von Versuchen an, die das SnapCenter-Plug-in für VMware vSphere wiederholt versucht, eine Abfrage über VMware-Snapshots zu senden, weil „...Zeitlimit für I/O-Zurückhaltung...“ Fehler während einer Sicherung.

+
Der Standardwert ist „0“.

* *vmware.quiesce.retry.interval=5*
+
Gibt die Zeitdauer in Sekunden an, die das SnapCenter-Plug-in für VMware vSphere zwischen dem Senden der Abfragen zum VMware-Snapshot „...Zeitlimit für das Abhalten von I/O...“ wartet. Fehler während einer Sicherung.

+
Der Standardwert ist „5“.

* *vmware.query.unresolved.retry.delay= 60000*
+
Gibt die Zeit in Millisekunden an, die das SnapCenter-Plug-in für VMware vSphere zwischen dem Senden der Abfragen zu nicht aufgelösten Volumes wartet, da „...Zeitlimit für das Abhalten von I/O...“ Fehler. Dieser Fehler tritt auf, wenn ein VMFS-Datastore geklont wird.

+
Der Standardwert ist „60000“ (60 Sekunden).

* *vmware.reconfig.vm.retry.count=10*
+
Gibt die maximale Anzahl von Wiederholungen an, die das SnapCenter-Plug-in für VMware vSphere wiederholt versucht, eine Abfrage zur Neukonfiguration einer VM zu senden, da „...Zeitlimit für das Abhalten von I/O...“ Fehler.

+
Der Standardwert ist „10“.

* *vmware.reconfig.vm.retry.delay=30000*
+
Gibt die maximale Zeit in Millisekunden an, die das SnapCenter-Plug-in für VMware vSphere zwischen dem Senden von Abfragen zur Neukonfiguration einer VM wartet, da „...Zeitlimit für die Einschränkung von I/O...“ Fehler.

+
Der Standardwert ist „30000“ (30 Sekunden).

* *vmware.Rescan.hba.retry.count=3*
+
Gibt die Zeit in Millisekunden an, die das SnapCenter-Plug-in für VMware vSphere zwischen dem Senden der Abfragen zum erneuten Scannen des Host-Bus-Adapters wartet, da „...Zeitlimit für das Halten von I/O...“ Fehler.

+
Der Standardwert ist „3“.

* *vmware.rescan.hba.retry.delay=30000*
+
Gibt die maximale Anzahl von Wiederholungen an, die das SnapCenter-Plug-in für VMware vSphere zum erneuten Scannen des Host-Bus-Adapters verwendet.

+
Der Standardwert ist „30000“.


